import { faSignIn } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import type { NextPage } from "next";
import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import MainContent from "../components/HomePage/MainContent";
import MainLeftSidebar from "../components/HomePage/MainLeftSidebar";
import MainRightSidebar from "../components/HomePage/MainRightSidebar";

const Home: NextPage = () => {
  const { data: session } = useSession();
  if (!session) {
    return (
      <div>
        <Head>
          <title>AzriClone || Login</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="main-container">
          <div className="main-left-sidebar"></div>
          <div className="main-content">
            <div className="flex flex-col items-center justify-center text-xl mt-20">
              <h3>
                Welcome to{" "}
                <span className=" text-accentMain hover:text-accentDark transition-all font-semibold">
                  {" "}
                  AzriClone
                </span>
              </h3>
              <h3>
                A clone of Facebook using fake data from{" "}
                <a
                  href="https://dummyapi.io/"
                  className=" underline underline-offset-4 text-textMedium"
                >
                  dummyapi.io
                </a>
              </h3>
              <h2 className="mx-auto text-3xl block text-center mt-10">
                Please Login First
              </h2>

              <button
                onClick={() => signIn()}
                className="icon-round-text-btn w-fit text-accentMain pr-6 mt-5 bg-primaryMediumLight"
              >
                <FontAwesomeIcon
                  icon={faSignIn}
                  className="text-xl w-8 text-accentMain"
                />
                <p className="text-textMedium font-normal text-xl">Login</p>
              </button>
            </div>
          </div>
          <div className="main-right-sidebar "></div>
        </main>
      </div>
    );
  } else {
    return (
      <div>
        <Head>
          <title>AzriClone || Home</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="main-container ">
          <MainLeftSidebar />
          <MainContent />
          <MainRightSidebar />
        </main>
      </div>
    );
  }
};

export default Home;
