import type { NextPage } from "next";
import Head from "next/head";
import MainContent from "../components/HomePage/MainContent";
import MainLeftSidebar from "../components/HomePage/MainLeftSidebar";
import MainRightSidebar from "../components/HomePage/MainRightSidebar";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main-container ">
        <MainLeftSidebar />
        <MainContent />
        <MainRightSidebar />
      </main>
    </div>
  );
};

export default Home;
